### ISSUE TITLE
Need an option to control padding in square (rounded corner) icons

### ISSUE THREAD

**Issue by ShubhamBadal** [romannurik/AndroidAssetStudio#110]
When a large icon is supplied to generate icons in square shape (which actually generates rounded corners not square actually, should be renamed), it trims a lot of edges thereby making the entire icon smaller. Please provide an option to control this trimming margin and padding.

**Comment by Venryx** [comment]
Made a fork of the project with reduced padding--keeping just enough padding so that the shadow doesn't get cropped at all: https://venryx.github.io/AndroidAssetStudio/icons-launcher.html

The exact reduction in padding is 1/24 of the icon size, for each resolution--so e.g. 2px less padding on each side, for the 48x84 icon. (I did it for all the icon sizes except for the web 512x512, because I didn't notice it at first, so I thought the mipmap-xxxhdpi (192x192) resolution was the highest, and used that as the base for the modified mask image files)
