### ISSUE TITLE
xxxhdpi not available for action icons

### ISSUE THREAD

**Issue by javmarina** [romannurik/AndroidAssetStudio#14]
Xxxhdpi is currently available for launcher icons, but not for action icons (just xxhdpi). It would be an awesome feature.

**Comment by tajchert** [comment]
+1

**Comment by joerogers** [comment]
Just fixed it for myself. Try this: http://joerogers.github.io/AndroidAssetStudio/

**Comment by bryant1410** [comment]
According to [this](https://developer.android.com/guide/practices/screens_support.html#xxxhdpi-note) xxxhdpi assets are only needed for launcher icons, which are already provided by this tool.

#44 adds this functionality.

**Comment by joerogers** [comment]
This started coming up when Android Studio 1.1 started flagging for not having XXXHDPI assets for items other than the launcher. The Nexus 6 along with several other devices are running above the XXHDPI density. This [android blog](http://android-developers.blogspot.com/2014/10/getting-your-apps-ready-for-nexus-6-and.html) talks about the need to consider adding them. I wish I could support 5.0+ only so that I could ship exclusively with vector drawables instead.

**Comment by bryant1410** [comment]
Yeah we were talking about the same in the #44 PR.

Everybody wishes we could support only the latest :smile:

**Comment by joerogers** [comment]
BTW my change fixes all icons including action bar, generic, notification and support for 9 patches at xxxhdpi. #44 only did action bar. I needed a more robust patch.

**Comment by bryant1410** [comment]
Why don't you send a PR?

**Comment by joerogers** [comment]
Done. I was letting a few friends "validate" everything seemed to be working the last two days.
