### ISSUE TITLE
Support for Adaptive Launcher Icons (Android O)

### ISSUE THREAD

**Issue by jamesmontemagno** [romannurik/AndroidAssetStudio#160]
It would be nice to add this functionality in to the Asset Studio <3

**Comment by radefffactory** [comment]
Also adaptive icons for the App Shortcuts. This is missing from the Android Studio also. Basically there's no way (there's no tool) for creating adaptive app shortcuts instead of using launcher adaptive icons generator in the Android Studio. But there I cannot size the inside image properly according to the guidelines.

**Comment by adamreisnz** [comment]
It would be great to have this tool updated to be able to generate adaptive icons. The current icons are generated at 48dp but that's not enough for the new adaptive icon guidelines.

**Comment by martin-braun** [comment]
@tibbi It would be nicer to extend the existing version in a way that the background can be ticked off without breaking it's current implementation. Then you could make a PR, so this feature could make it into the product.

**Comment by romannurik** [comment]
After many years of thinking about doing it... I finally did it. It's not perfect (still generates PNGs / doesn't use vector graphics), but it works. 🤷🏻 

Done in 951c463ef846fdf89d0b413938b1c1b010aa0834
