### ISSUE TITLE
Add documentation for running locally

### ISSUE THREAD

**Issue by drw158** [romannurik/AndroidAssetStudio#36]
Is there a way to run this locally?

**Comment by anthonycr** [comment]
This will run in Firefox simply by building it with **make.sh** and then opening the **index.html** in the browser and navigating to the page you want. I couldn't run it the same way in Chrome because Chrome blocks the image rendering when opening the local html file (it throws a SecurityError saying tainted canvases may not be exported), but it will work fine if you're running a webserver on your computer and you open it in localhost.

**Comment by drw158** [comment]
Sorry for my ignorance; how do I run make.sh?

**Comment by anthonycr** [comment]
It's a shell script which can be run in the terminal on a [Linux OS](http://en.wikipedia.org/wiki/Shell_script) or in [Cygwin on Windows](http://stackoverflow.com/questions/6413377/is-there-a-way-to-run-bash-scripts-on-windows). Additionally, I had to move the location of the `/lib` folder after building because for some reason when I built it the path ended up being `/lib/lib`.

**Comment by kwood1138** [comment]
I fixed the `/lib/lib` issue on my local copy by removing the `mkdir -p _gh-pages/lib` line.

**Comment by JoseGD** [comment]
I have listed the steps to run **make.sh** succesfully here: https://github.com/romannurik/AndroidAssetStudio/issues/85#issuecomment-235605723

Also I recommend using @anthonycr fork, it has a handy "Shadow intensity" feature that solves the long shadow's visibility problem

**Comment by romannurik** [comment]
The README is now updated.
