### ISSUE TITLE
Launcher icon: transparent background for shapes

### ISSUE THREAD

**Issue by anotherdev** [romannurik/AndroidAssetStudio#66]
When I use square shape, I get a background color in the transparent part of my launcher icon (default white). Can we add transparent option?

**Comment by romannurik** [comment]
Can you post a screenshot and example output?

**Comment by jon80** [comment]
Not really, as the company I used to provide support to seems to have moved on to greener pastures, however you may if you wish write to the following to follow up whether this bug is still relevant for them as I am not sure what upgrades were made in the development environment:
T: +356-27761003 E: sales@richmoore-anderson.com Richmoore and Anderson InternationalMalta (EU), Pieta, 3rd Floor Merlin House, Joe Gasan StreetAttn: Messrs La Rosa/Software Development(http://www.richmoore-anderson.com/contact-us/)
J. Camilleri
Malta, EU


Date: Fri, 25 Sep 2015 06:23:16 -0700

**Comment by anotherdev** [comment]
Hmm, the launcher icon generator changed? There is less option now, but the result is the same.

![stackapp](https://cloud.githubusercontent.com/assets/2402083/10102168/26e4f312-63c7-11e5-81bd-a977615e50ea.png)

Output

![ic_launcher](https://cloud.githubusercontent.com/assets/2402083/10102218/71525688-63c7-11e5-872f-36e11ce865a2.png)


![screen shot 2558-09-25 at 20 40 02](https://cloud.githubusercontent.com/assets/2402083/10102163/1a13e1a2-63c7-11e5-97f2-9111e1839d4e.png)

**Comment by romannurik** [comment]
This is working as expected. To keep the transparent part transparent you'll need to choose None for the shape.

**Comment by jon80** [comment]
I do not understand why you closed it, it might have been a useful suggestion for improving user interaction.
J. Camilleri
Malta, EUhttps://delicious.com/jon80

Date: Fri, 25 Sep 2015 09:44:27 -0700
