### ISSUE TITLE
Build fails when I run make.sh

### ISSUE THREAD

**Issue by arunabhdas** [romannurik/AndroidAssetStudio#85]
When I run make.sh on mac, the build fails with the following error 

==> ./make.sh 
Buildfile: /Users/coder/repos/ad/githubrepos/AndroidAssetStudio/src/js/build.xml

BUILD FAILED

<path-to>/AndroidAssetStudio/src/js/build.xml:25: Cannot find <path-to>/AndroidAssetStudio/src/js/${flintjs.dir}/flintjs.build.xml imported from <path-to>/AndroidAssetStudio/src/js/build.xml

**Comment by romannurik** [comment]
The now very-antiquated build system requires [flintjs](https://code.google.com/p/flintjs/). Should definitely port over to gulp at some point.

**Comment by arunabhdas** [comment]
Could you please document the steps to build using flintjs in README?

**Comment by JoseGD** [comment]
For anyone trying to build AndroidAssetStudio as it is, you have to do the following:

1. Download [flintjs](https://code.google.com/p/flintjs/), place the .zip contents in a path of your choice
2. Modify the line in **src/js/build.xml** referring to flintjs:
`<import file="<your_path>/flintjs-0.1.1/flintjs.build.xml"/>`
3. Comment the line `mkdir -p _gh-pages/lib` in **make.sh** (tip from https://github.com/romannurik/AndroidAssetStudio/issues/36#issuecomment-77605595)
4. Run **make.sh**

Also I had to install ant since I never used it before.
