### ISSUE TITLE
Setting padding to 0dp does not remove padding

### ISSUE THREAD

**Issue by eriksalhus** [romannurik/AndroidAssetStudio#92]
Setting padding to 0dp works vertically but the horizontal padding(left and right padding) is still there. Changing the padding removes some part of the padding, but it seem as there is an additional padding set for left and right. Is this a feature or a bug?

I would expect that setting the property "Trim" and "Padding" to 0dp, all padding/space around the image/icon will be removed but that is not the case.

**Comment by bendaniel10** [comment]
I'm having this issue too, is there any workaround?

**Comment by romannurik** [comment]
This is working as intended. If you need to deviate from the launcher icon specifications please fork the code.

**Comment by Venryx** [comment]
Fair enough; I didn't realize that was part of the icon specifications.

Any idea why they would recommend adding completely unused space around the edges? Just seems like a waste of image space to me.

**Comment by romannurik** [comment]
Generally the space is to account for shadows as well as irregular shapes. The idea is that icons should look roughly evenly sized (this is why the circle extends beyond the bounds of the square foot example). Irregular shapes may need to extend out even further, hence the extra space.

**Comment by Venryx** [comment]
Made a fork of the project as you suggested. : )

The modified version keeps just enough padding so that the shadow doesn't get cropped at all: https://venryx.github.io/AndroidAssetStudio/icons-launcher.html

The exact reduction in padding is 1/24 of the icon size, for each resolution--so e.g. 2px less padding on each side, for the 48x84 icon. (I did it for all the icon sizes except for the web 512x512, because I didn't notice it at first, so I thought the mipmap-xxxhdpi (192x192) resolution was the highest, and used that as the base for the modified mask image files)
